version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: luminex_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_luminex
      POSTGRES_PASSWORD: password_secret
      POSTGRES_DB: luminex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_luminex"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: luminex_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@luminex.id
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
